### ISSUE TITLE
TODO list for Team beta testing preparation

### ISSUE THREAD

**Issue by MarkWendler** [X2Cscope/pyx2cscope#21]
Update links:
* Update links on readme.md to point the github page docs --> https://x2cscope.github.io/pyx2cscope/ (Yash)
* update project.toml update --> https://x2cscope.github.io/pyx2cscope/ (Yash)
* Update start page of legacy document https://x2cscope.github.io/ -->https://x2cscope.github.io/pyx2cscope/ (Mark)

Update doc:
* Turn on test documentation (Edras, split the task)
* Update example elf links to a txt file, add txt file to skip worktree? (Edras)
* Update How to and overview pages (Yash)
* List actual limitations (Yash)

**Comment by edras** [comment]
Here are the initial tasks to fix documentation at  [https://github.com/X2Cscope/pyx2cscope/tree/fix-documentation](this) branch.
I replaced on that branch black and isort for ruff.
Ruff is now checking docstring, linter, imports and docstring style. I included/replaced it on the requirements and quality files as well on the workflow at github actions (for this branch only).

To use it type on the terminal at the root folder:
`ruff check .`

and to auto fix what is possible to auto fix:
`ruff check . --fix`

If you run this command, there are actually 183 errors. I fixed already many one to reach this number :)
My suggestion by now would be to split documentation fix task force as:

@edras /tests
@MarkWendler  variable.py and x2cscope.py
@yashagarwal-314 /parser and /gui

we will still have examples folder and mchplnet submodule.
I would remove mchplnet from ruff test on pyX2CScope once it is a submodule.
In this case, only the examples folder will be missing. we may discuss this after this first task is done.

**Comment by X2Cscope** [comment]
We need to document subclasses and overrides as well:
[PEP 257](https://www.python.org/dev/peps/pep-0257/):

The docstring for a class should summarize its behavior and list the public methods and instance variables. If the class is intended to be subclassed, and has an additional interface for subclasses, this interface should be listed separately (in the docstring). The class constructor should be documented in the docstring for its __init__ method. Individual methods should be documented by their own docstring.

If a class subclasses another class and its behavior is mostly inherited from that class, its docstring should mention this and summarize the differences. Use the verb "override" to indicate that a subclass method replaces a superclass method and does not call the superclass method; use the verb "extend" to indicate that a subclass method calls the superclass method (in addition to its own behavior).

**Comment by X2Cscope** [comment]
My par tis done, but I hit some problems I could not work around.

"pyx2cscope\xc2scope.py:161:9: PLR0913 Too many arguments in function definition (6 > 5)"
This requires some restructuring the implementation of scope functionalities. 
Also the documentation of the scope functionalities are very weak. Actually these would be the most important. Before I fix it we need to sync  to agree on the proper way.



![image](https://github.com/X2Cscope/pyx2cscope/assets/73351552/e06ae2ad-1ceb-4585-816d-9a563009d586)

**Comment by edras** [comment]
> My par tis done, but I hit some problems I could not work around.
> 
> "pyx2cscope\xc2scope.py:161:9: PLR0913 Too many arguments in function definition (6 > 5)" This requires some restructuring the implementation of scope functionalities. Also the documentation of the scope functionalities are very weak. Actually these would be the most important. Before I fix it we need to sync to agree on the proper way.
> 
> ![image](https://private-user-images.githubusercontent.com/73351552/336807161-e06ae2ad-1ceb-4585-816d-9a563009d586.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjUzODgsIm5iZiI6MTcxNzY2NTA4OCwicGF0aCI6Ii83MzM1MTU1Mi8zMzY4MDcxNjEtZTA2YWUyYWQtMWNlYi00NTg1LTgxNmQtOWE1NjMwMDlkNTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA5MTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxN2M1YmNjNDI5MWIzNjM1OGVkMTE1ZmViMjI5MjAwNWY3OTkwOWNhYmM5ZjgwNGY3Y2FmNzNjYWU0N2ZlY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fATtrKacsC8upWqlTGFzavB7-wtoup8okAYXQ83mSco)

Specifically about this function, I would place a **# noqa: PLR0913.** 
This method needs to have the self argument, but this argument does not belong to the user interface.
Other approach would be to create a dataclass for these arguments and pass like an object of type "TriggerSettings".
