### ISSUE TITLE
documentation and source instruction

### ISSUE THREAD

**Issue by tronicbaumi** [X2Cscope/pyx2cscope#26]
from my point of view the documentation should not show the installation into a virtual environment, this is confusing for non experienced people, experienced people will do this automatically.

Maybe the --force installation should also be mentioned in the documentation

source instruction isn't working on my side

**Comment by MarkWendler** [comment]
Hi, 
I agree, we should support global installation by default. 

--force installation--> It is better to use:
`pip install --update pyx2cscope `

pip is a package manager. If pyx2cscope is already installed, it will not install again. Must be asked to update it. --force removes then install again.

**Comment by edras** [comment]
I included instruction for windows and how to update pyx2cscope if it is already installed as suggest by @MarkWendler
