### ISSUE TITLE
Debug mode off even it is enabled?

### ISSUE THREAD

**Issue by MarkWendler** [X2Cscope/pyx2cscope#27]
I enabled debug mode with -l DEBUG. Still debug mode off.

```
(.venv) C:\_projects>py -m pyx2cscope -w -l DEBUG
Listening at http://localhost:5000
 * Serving Flask app 'pyx2cscope.gui.web'
 * Debug mode: off
```

**Comment by edras** [comment]
By default all the logs are stored at a log file located where the program is called.
I added an additional argument:  "-c", "--log-console", if this is present, the log will be be present at the console as well.

Regarding the debug mode: off  message on Flask server, this is the mode how the server works, in production or in debug mode. The server is always running in production mode. The messages generated by the server obey the log level used at
the program beginning.
