### ISSUE TITLE
Create installer and executables

### ISSUE THREAD

**Issue by MarkWendler** [X2Cscope/pyx2cscope#29]
Create releases
- Executables:
    - QT GUI
    - WEB interface
- Installer

**Comment by yashagarwal-314** [comment]
Beta version available.

**Comment by MarkWendler** [comment]
DEpends on #35

**Comment by MarkWendler** [comment]
Use cx_freeze for now.

**Comment by MarkWendler** [comment]
Add shortcut to web interface argument to the zip file.
Check how to pass exe arguments to main python routine. Maybe cx_freeze options?

**Comment by X2Cscope** [comment]
cx_freeze supports multiple platform, but cannot crosscompile. The description is misleading. 
pyinstaller will be used as it is the "standard"/more popular and supported by GH actions as well.


cx_freeze description just for ref:
_"cx_Freeze creates standalone executables from Python scripts with the same performance, is cross-platform and should work on any platform that [Python ](https://www.python.org/) works on."_

**Comment by X2Cscope** [comment]
Questions/challanges:
 - onefile option: Uses run time compression UPX. Slows down the start. We might need to implement splash screen.
 - withouth console option: Web interface starts, but proccess cannot be closed as no window is for the server process is opened.

 - Web interface and QT Gui interface bundling or separated exe still a question.
 - Creating artifacts only on release?
 - Version number, where to show, file name and/or GUI?
