### ISSUE TITLE
Merge Parsers for xc16, xc32 and xc-dsc

### ISSUE THREAD

**Issue by edras** [X2Cscope/pyx2cscope#35]
We are using pyelf for 32 bit devices and xc16-read-elf for 16 bit devices.

I suggest to use read-elf from microchip for all architectures.

First step is to check if the output from read-elf is similar among compilers.
If they are, we may merge the read-elf for 32 and dsc devices.

**Comment by MarkWendler** [comment]
Focus on global explicit variables only (skip pointers for now)
Make sure reliable list of variable and adresses are correct
Contents of the pointer not important

**Comment by edras** [comment]
Just to document here as the initial comment was to use the read-elf for both compilers. 
The decision changed to use the official pyelf-tool from the community.
By now all different elf files are supported xc-16, xc-32, and xc-dsc.
