### ISSUE TITLE
CLean and minimize  __main__.py

### ISSUE THREAD

**Issue by X2Cscope** [X2Cscope/pyx2cscope#40]
There are way too much import on main.py.

If I encounter an issue with qt, GUI or any dependency, I still not cant check the version or print --help options.

Like here:

```
python -m pyx2cscope --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Lib\site-packages\pyx2cscope\__main__.py", line 17, in <module>
    from pyx2cscope.gui.watchView.minimal_gui import X2cscopeGui
```

If I just want to print help or version, it loads big ma python libs:

- Slows the process even if I just want to print version loads big libs.
- In case dependency issue broke the whole pyX2Cscope.

Solution:
Move GUI related libs to the gui/main.py or something similar.

**Comment by edras** [comment]
#45  this Pull-request address this issue
