### ISSUE TITLE
Support pyx2cscope.__version__

### ISSUE THREAD

**Issue by MarkWendler** [X2Cscope/pyx2cscope#8]
The __version__ attribute, recommended by Python Enhancement Proposals (PEP), is available in many packages.

[PEP 396 – Module Version Numbers | peps.python.org](https://peps.python.org/pep-0396/)
[PEP 8 – Style Guide for Python Code | peps.python.org](https://peps.python.org/pep-0008/#module-level-dunder-names)
Note that not all packages have the __version__ attribute because it is not mandatory.

In addition to the __version__ attribute, some packages, such as NumPy and pandas, provide functions and attributes that display more detailed information.

[Check NumPy version: np.version](https://note.nkmk.me/en/python-numpy-version/)
[Check pandas version: pd.show_versions](https://note.nkmk.me/en/python-pandas-version/)
Note that the __version__ attribute is not set for the standard library modules such as math and os. Modules in the standard library do not have individual versions but follow the Python version.

**Comment by edras** [comment]
This issue is addressed at #22
