### ISSUE TITLE
Simplify serial support by lnet 1.

### ISSUE THREAD

**Issue by MarkWendler** [X2Cscope/pyx2cscope#9]
We were using serial connection in 99% of the cases, would make sense to simplify its usage by LNET

For a simple serial connection I do not see a reason to use InterfaceFactory. Why not support like this:

```
import serial
ser = serial.Serial('COM3', 115200)
l_net = LNet(serial_connection)
```

Currently looks too complex for me than it is actually neccesary:
```
from mchplnet.interfaces.factory import InterfaceFactory
from mchplnet.interfaces.factory import InterfaceType as IType

# Initialize serial communication
serial_port = "COM8"
baud_rate = 115200
serial_connection = InterfaceFactory.get_interface(
    IType.SERIAL, port=serial_port, baudrate=baud_rate
    )

# Initialize LNet and VariableFactory
l_net = LNet(serial_connection)
```

**Comment by yashagarwal-314** [comment]
I and Edras came up with this idea to make it easier for the future, once we start CAN and TCP/IP. 

but if we should have a more straightforward implementation, I will make it by the next release.
